version: "3.8"

services:
  database:
    build: ./series-tracker-database
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: anime_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
    ports:
      - "3306:3306"

  backend:
    build: ./series-tracker-backend
    container_name: go-backend
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: anime_db
      PORT: 8080
    command: ["./server"]

